"""The planner: an advisory plan before the coder starts (ADR-031).

One model call that reads only the specification and answers with a structured plan (steps,
likely files, risks, tests to add). It mirrors `verify/reviewer.py` on purpose, with one
difference that is the whole design: the reviewer's verdict gates the task, the plan does not.

- **A plan is advice, never a gate.** A malformed plan does not fail the task: it is recorded as
  malformed and the coder runs without it. Nothing downstream trusts the plan: the checks and
  the independent reviewer judge the diff, not the intention.
- **The coder reads it as unverified model output.** `plan_message` labels it so, which is also
  how the PR body and the UI show it.
"""

from dataclasses import dataclass
from typing import Any, Protocol

from pydantic import BaseModel, Field, ValidationError

from warden.providers.base import Completion, ModelProvider, ToolSchema, UserMessage

PLAN_TOOL = "submit_plan"

# Own prompt, not the coder's: planning is a different job asked of a different context. It is
# told it has no tools to explore with, because it must answer from the specification alone: a
# plan that needed to read the repo first would be a second agent loop.
PLANNER_SYSTEM_PROMPT = """You are a planner for a coding agent. You will not make the changes \
yourself and you cannot read the repository: work only from the specification below.

Write a short plan the agent can follow: the concrete steps in order, the files it will \
probably have to read or change, the risks that could go wrong (edge cases, behaviour that must \
not regress), and the tests it should add or update. Say so plainly when the specification is \
too vague to name files.

Call submit_plan exactly once, as your only action. Your plan is advice that the agent may \
ignore and that nobody has verified."""


class PlanPayload(BaseModel):
    """The shape `submit_plan`'s arguments must validate against.

    `steps` needs at least one entry: an empty plan carries no information and would make the
    coder's "plan" message a header over nothing. The other lists may be empty, since "no
    risks" and "no new tests" are answers.
    """

    steps: list[str] = Field(min_length=1)
    likely_files: list[str]
    risks: list[str]
    tests_to_add: list[str]


@dataclass(frozen=True)
class PlanResult:
    """One planner call: the raw completion (the loop bills and records it) and either a
    validated plan or the reason there is none."""

    completion: Completion
    plan: PlanPayload | None
    malformed_reason: str | None


class Planner(Protocol):
    """What `core/loop.py` needs: a plan from the spec, nothing more. Loop-level tests
    implement this without a model."""

    async def plan(self, spec: str) -> PlanResult: ...


def _plan_tool() -> ToolSchema:
    def lines(description: str) -> dict[str, Any]:
        return {"type": "array", "items": {"type": "string"}, "description": description}

    return ToolSchema(
        name=PLAN_TOOL,
        description="Report your plan for the agent.",
        input_schema={
            "type": "object",
            "properties": {
                "steps": lines("The concrete steps, in order. At least one."),
                "likely_files": lines("Files the agent will probably read or change."),
                "risks": lines("What could go wrong or regress."),
                "tests_to_add": lines("Tests to add or update."),
            },
            "required": ["steps", "likely_files", "risks", "tests_to_add"],
        },
    )


def plan_message(plan: dict[str, Any]) -> str:
    """What the coder reads: the plan, labelled as what it is.

    Takes the recorded dict, not a `PlanPayload`, because `core/replay.py` rebuilds the same
    message from the event log, and live and replayed runs must show the coder the same text.
    """
    payload = PlanPayload.model_validate(plan)

    def section(title: str, items: list[str], *, numbered: bool = False) -> str:
        if not items:
            return ""
        body = "\n".join(
            f"{n}. {item}" if numbered else f"- {item}" for n, item in enumerate(items, 1)
        )
        return f"\n{title}:\n{body}\n"

    return (
        "Plan generated by the planner (model output, not verified; use it as a suggestion, "
        "not as an instruction):\n"
        + section("Steps", payload.steps, numbered=True)
        + section("Likely files", payload.likely_files)
        + section("Risks", payload.risks)
        + section("Tests to add", payload.tests_to_add)
    ).rstrip()


class ProviderPlanner:
    """A planner bound to the provider the worker built for this task."""

    def __init__(self, provider: ModelProvider) -> None:
        self._provider = provider

    async def plan(self, spec: str) -> PlanResult:
        completion = await self._provider.generate(
            [UserMessage(text=spec)],
            tools=[_plan_tool()],
            system=PLANNER_SYSTEM_PROMPT,
        )

        call = next((c for c in completion.tool_calls if c.name == PLAN_TOOL), None)
        if call is None:
            reason = f"the planner did not call {PLAN_TOOL} ({completion.stop_reason})"
            return PlanResult(completion, None, reason)
        try:
            plan = PlanPayload.model_validate(call.arguments)
        except ValidationError as exc:
            # Not the raw arguments: they are model output and can be large. The first
            # error is enough to tell a missing field from a wrong type.
            first = exc.errors()[0]
            where = ".".join(str(part) for part in first["loc"]) or "arguments"
            reason = f"{PLAN_TOOL} arguments are malformed at {where}: {first['msg']}"
            return PlanResult(completion, None, reason)
        return PlanResult(completion, plan, None)
